author:
  name: Paolo Salvatori
  twitter: babosbird
  linkedin: paolo-salvatori
  location: Milan, Italy
twitter:
  username: babosbird
  card: summary
theme: jekyll-theme-cayman
title: Create a private Azure Kubernetes Service cluster using Terraform and Azure DevOps
description: This sample shows how to create a private AKS cluster using Terraform and Azure DevOps.
markdown: kramdown
highlighter: rouge
relative_links:
  enabled: true
  collections: true
