theme: jekyll-theme-tactile
title: Create a private Azure Kubernetes Service cluster using Terraform and Azure DevOps
description: This sample shows how to create a private AKS cluster using Terraform and Azure DevOps.
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
